### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by MitchellThompkins** [arecarn/cpp-sandbox#1]
https://github.com/arecarn/c-and-cpp-sandbox/blob/5603dfac149ac271fbdca94ffaf0c57296314fa8/src/questions/arrays/CMakeLists.txt#L22

I think you try to build and link the same executable twice, causing the build to fail with:
```
 add_test given test NAME "zero_matrix.test" which already exists in this
  directory.
```

**Comment by arecarn** [comment]
Yeah, I just committed real quick just to sync my changes, and left in a copy an paste error.
